[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cmcc-assistant"
version = "0.1.0"
authors = [
  { name="Your Name", email="you@example.com" },
]
description = "A real-time voice control center for CMCC's smart exhibition hall."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "loguru==0.7.2",
    "numpy==2.2.6",
    "sherpa-onnx>=1.10.3",
    "onnxruntime>=1.19.0",
    "kaldi-native-fbank>=1.19.4",
    "soundfile>=0.12.1",
    "pandas==2.3.1",
    "pydantic-settings==2.10.1",
    "chromadb==1.3.3",
    "langchain==1.1.0",
    "langchain-openai==1.0.2",
    "langchain-chroma==0.2.5",
    "fastapi==0.116.1",
    "uvicorn==0.35.0",
    "python-multipart==0.0.18",
    "av==16.0.1",
    "httpx==0.27.2",
    "modelscope==1.28.1",
    "scipy==1.14.1",
    "rank_bm25==0.2.2",
    "jieba==0.42.1",
]

[project.optional-dependencies]
mic = [
    "pyaudio",
]
ollama = [
    "langchain-ollama",
]

[tool.setuptools.packages.find]
where = ["src"]
